### ISSUE TITLE
Issue pra IssueAi

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#1]

**Comment by JoseRenan** [comment]
IssueAi

**Comment by thayannevls** [comment]
Blz, tem algumas ideias de readme? Não o readme, mas acho bom a gente começar com o código de conduta também, e a licença. Seguindo conselhos desse site: https://opensource.guide/starting-a-project/

**Comment by thayannevls** [comment]
Minhas ideias:

- Deixar claro que qualquer pessoa pode participar de uma discussão
- Não é permitido roubar ideias sem consentimento, isso talvez possa ser barrado com a licença
- Tentar sempre ter espírito amigável, toda ideia é bem vinda
- Talvez templates de issues

**Comment by FannyVieira** [comment]
Além do código de consulta, readme e licença, seria legal nesse repo, colocar o contributing e o template das issues e pull requests, a ideia é que esse repo sirva como padrão para os outros.

**Comment by thayannevls** [comment]
A gente definindo bem o código de conduta ele pode ser usado para todos esses repositórios, primeiro a gente tem que definir nossos valores e objetivos eu acho

**Comment by JoseRenan** [comment]
@thayannevls, acho que não é necessário isso de roubar ideias, a gente tem de incentivar forks e a licença cuida do resto

**Comment by thayannevls** [comment]
Bem talvez agora pudessemos discutir a dinâmica de Issues, será que a adição de templates seria uma boa?

**Comment by thayannevls** [comment]
Na verdade vou quebrar essa issue em algumas issues, com coisas básicas pra algo open source

- [ ] Licença
- [ ] Readme
- [ ] Código de conduta
- [ ] Manual de Contribuição

**Comment by JoseRenan** [comment]
Nesse caso a gente pode fechar essa né? @thayannevls

**Comment by thayannevls** [comment]
Acho que sim @JoseRenan

**Comment by joseims** [comment]
Gente amei a ideia

**Comment by thayannevls** [comment]
Mto obg @joseims ❤️ Se sinta a vontade para comentar algo ou contribuir, bem vindo haha
