### ISSUE TITLE
Remover ordenação por star dos projetos

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/IssueAi#102]
**Descrição da melhoria:**
Seria legal não ter essa ordenacao inicial dos projetos por star, atualmente os projetos do opendev sempre ficam no inicio.

**Comment by joaopslins** [comment]
Pelo que estou vendo quando abro o https://issueai.opendevufcg.org, ele já tá ordenado por star, não? Ou é coincidência?

**Comment by fanny** [comment]
Ops, tens razão @joaopslins, seria dar um shuffle msm

**Comment by joaopslins** [comment]
Talvez colocar um dropdown pra escolher a ordenação, isso resolve dois problemas:

1 - Fica visível qual o critério de ordenação, que hoje é implícito
2 - Permite o usuário escolher o que ele prefere

**Comment by fanny** [comment]
Concordo contigo, tens interesse em fazer?

**Comment by joaopslins** [comment]
Yep! Posso fazer sim. Pode marcar como Assignee.

**Comment by fanny** [comment]
Show!
