### ISSUE TITLE
Leites, um problema?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#11]
Repositórios de implementações antigas de cadeiras como LEDA são os mais comuns na cadeira de computação. Também como compartilhamento de leites como o GALHERA-CC. Também é o mais fácil de se ter contribuição dos alunos, e também ajuda muita gente.

Acho que seria meio estranho a gente deixar esses tipos de repositórios de fora da organização... O problema é como fazer isso não ser visto com maus olhos. Citei o  [Tamburetei](#3), mas algumas pessoas vieram comentar comigo se isso dá certo ou não.

O que acham? Publicar leites e implementações antigas de roteiros de LEDA, ou cadeiras como P2 é um problema? Tem alguma ideia de como a gente pode fazer diferente dos repositórios que já existem?

**Comment by paulojbleitao** [comment]
Acho que tudo bem publicar leites desde que não seja de cadeiras como LEDA, em que os roteiros são os mesmos em todos os períodos. Fazer isso pode acabar atrapalhando o aprendizado de alguns, por se sentirem tentados a copiar. De resto, acredito ser uma grande ajuda.

**Comment by thayannevls** [comment]
@paulojbleitao O problema é que implementações antigas de roteiros de LEDA são bem comuns na vdd

**Comment by FannyVieira** [comment]
Mas o problema que ele citou é bem recorrente, muita gente acaba copiando o código, acho que seria legal ter a implementação, mas não na mesma estrutura de LEDA, de modo que a pessoa usasse para entender o comportamento.

**Comment by thayannevls** [comment]
Então algoritmos exemplares e botar regra pra não se ter os roteiros em si

**Comment by paulojbleitao** [comment]
> @paulojbleitao O problema é que implementações antigas de roteiros de LEDA são bem comuns na vdd

Ainda assim, não acho muito bom incentivar as pessoas a irem consultá-las

**Comment by FannyVieira** [comment]
Isso @thayannevls

**Comment by thayannevls** [comment]
Obg @paulojbleitao e @FannyVieira . Tomei uma decisão aqui, vou criar um novo repositório com regras que levam em consideração o que vocês falaram aqui. ❤️
