### ISSUE TITLE
O que será o IssueAi

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/IssueAi#13]
Nas conversas de corredor, a gente falou sobre o IssueAi ser uma plataforma pra ajudar pessoas de CC na UFCG a achar projetos open source pra contribuir filtrando por linguagem, tecnologia, nível de dificuldade (iniciante, médio, avançado... baseado nas cadeiras de CC na UFCG msm) e etc... Inicialmente a gente teria os projetos que a gente citou no README.md (qualquer um pode adicionar mais) mas a ideia é que mais na frente as pessoas cadastrem seus projetos na plataforma e digam algumas informações sobre ele, pra gente conseguir filtrar e etc... o que vocês acham???

**Comment by thayannevls** [comment]
Acho que o complicado seria esses filtros extras, mas tipo, inicialmente a ideia seria apenas expor os projetos? Teria também a visualização de contribuidores e a rede de influência?

**Comment by thayannevls** [comment]
Fico pensando se a gente pode dar uma cara para os contribuidores tbm

**Comment by JoseRenan** [comment]
Pra uma primeira versão, a gente poderia deixar ele estático, com um showcase mostrando alguns projetos como os do README, só mostrando esse nível de dificuldade, e as tecnologias e linguagens usadas, eu tinha pensado nas tags do github, mas como a gente tá falando de projeto de universidade, acho que vai ser dificil controlar que todos que a gente mostre no showcase tenham um padrão com tags que digam as tecnologias que são usadas e tal. Por enquanto a gente poderia ficar sem a filtragem pq são poucos projetos, mas poderíamos trabalhar nisso paralelamente se tiver gente pra ajudar

**Comment by JoseRenan** [comment]
Mais uma ideia pro futuro, que no caso seria quando as pessoas pudessem cadastrar os projetos, poderiam ser os contribuidores dar um rating do projeto, no caso, sobre facilidade pra contribuir, o level do projeto bate com o que ele realmente é em dificuldade e tal

**Comment by thayannevls** [comment]
Gostei @JoseRenan . Acho que dá pra gente ter uma versão inicial rápida, quem sabe atrair ajuda.

O que imagino por agora e pensando simples, é usar alguma framework pra fazer o WEB e os repositórios serem mostrados utilizando a [Github API](https://developer.github.com/v4/), que é uma consulta bem simples.

Penso que a gente poderia começar com React.

**Comment by paulojbleitao** [comment]
Sobre a filtragem, acho que seria fácil implementar limitando para apenas algumas tags, por exemplo de linguagens e frameworks mais populares, além de dificuldade. O problema é que isso não escala muito bem, mas acho interessante pra ilustrar como o sistema funciona.

> Penso que a gente poderia começar com React.

Apoio com todas as minhas forças

**Comment by joseims** [comment]
Penso que talvez seja possivel criar um layout para colocar no read-me, e realizar a pesquisa fazendo um crawling no próprio read-me, e ao atualizar também mudaria o read-me, o risco é isso crescer demais e o layout ficar mt confuso, mas pouparia lógica.

**Comment by JoseRenan** [comment]
> O problema é que isso não escala muito bem
Pra iniciar eu acho que é okay, mas se tiver um número grande de projetos a gente precisa de um back pra cadastrar essas coisas, seria o próximo passo

**Comment by thayannevls** [comment]
> Penso que talvez seja possivel criar um layout para colocar no read-me, e realizar a pesquisa fazendo um crawling no próprio read-me, e ao atualizar também mudaria o read-me, o risco é isso crescer demais e o layout ficar mt confuso, mas pouparia lógica.

Tu pode explicar melhor @joseims ? Ou mostrar um exemplo

**Comment by joseims** [comment]
Tipo, invés da gente ter um banco de dados a gente usa o arquivo readMe, ao cadastrar no site, a gente vem no read me e adiciona o projeto no próprio arquivo. E na hora de procurar por repositorios, a gente ia procurar no proprio readme. 
Por exemplo se todo os repositorios fossem no formato
Nome - Linguagem - Framework - Complexidade
Ex : Pomadoro - Python - None - 1
Seria mt facil buscar achar isso no arquivo, entretanto isso limita mt o número de tags e impede o possivel crescimento do projeto.

Falando agora sobre o legado de um projeto que aida quase não existe, talvez faria sentido colocar a administração nas mãos do CAESI, visto que é sempre um grupo dentro de CC UFCG que sempre se renova.

**Comment by JuanBarros2** [comment]
Pensei em levar o conceito de times para ter um melhor aproveitamento da comunidade. Tipo assim: Tenho um problema com vue e não sei como resolver ele. Independente de meu time ser formado em vue ou não, certamente terá pessoas que programem outros projetos em vue e talvez possa responder a minha questão mais de perto. Aí que entrariam os times. Os usuários poderiam ir se inscrevendo em times que pudessem ajudar e isso facilitaria na hora de tirar dúvidas que não é possível simplesmente procurando em um stackoverflow da vida.

**Comment by FannyVieira** [comment]
> Tipo, invés da gente ter um banco de dados a gente usa o arquivo readMe, ao cadastrar no site, a gente vem no read me e adiciona o projeto no próprio arquivo. E na hora de procurar por repositorios, a gente ia procurar no proprio readme.
> Por exemplo se todo os repositorios fossem no formato
> Nome - Linguagem - Framework - Complexidade
> Ex : Pomadoro - Python - None - 1
> Seria mt facil buscar achar isso no arquivo, entretanto isso limita mt o número de tags e impede o possivel crescimento do projeto.
> 
> Falando agora sobre o legado de um projeto que aida quase não existe, talvez faria sentido colocar a administração nas mãos do CAESI, visto que é sempre um grupo dentro de CC UFCG que sempre se renova.

E como em tese os readmes serão padronizados a gente não deve ter muito problema ao tentar extrair isso de forma automática já que vai tá padronizado.

**Comment by JuanBarros2** [comment]
@OpenDevUFCG/racharia <- tipo assim

**Comment by joseims** [comment]
No caso acho que a gente precisaria de mais dados, tipo linguagem e que frameworks usa pelo menos, por isso também começo a achar que ficaria inviavel😕. No caso de você usar multiplos frameworks por exemplo. Ou em projetos mais complexos em que queremos adicionar mais dados.

**Comment by JoseRenan** [comment]
Pode ser estático sem ser no readme, tipo, pode ser um JSON grandão e a pessoa adiciona o seu via PR, mas com ele pela interface a gente poderia tratar duplicados e ownership do projeto mais facilmente, acho que é importante dar liberdade do negócio funcionar sem os maintainers precisarem estar olhando

**Comment by thayannevls** [comment]
pra github query api só precisa do array com os nomes dos repositórios... A query pra pegar eles com isso tem umas 5 linhas

**Comment by joseims** [comment]
Acho que a gente pode tirar parte do nosso trabalho e colocar no desenvolvedor, obriga ele a usar tags, e a gente pode fazer nossas tags especificas tipo f-react, ai se alguem quiser pesquisar por tag a gente olha os projetos em que o possui f-{nome da framework} ou l-{nome da linguagem}. Acho que padronizar tags é uma maneira de criar uma comunidade também, porque a gente cria regras da comunidade e ai essa noção de comunidade é criada.

**Comment by JoseRenan** [comment]
Mas ele teria de botar o nome do proj em algum canto né? não seria melhor colocar logo tudo lá?

**Comment by thayannevls** [comment]
A github api pega as linguagens usadas no repositório, e também captura aquelas tags que bota em cima. Se o dono do repositório colocar as frameworks como tags no repositório, temos tudo que precisamos

**Comment by thayannevls** [comment]
No caso ele só precisa botar tags que é usual botar, "react", "django" etc.. e teríamos mta coisa já sem precisar de um documento central

**Comment by joseims** [comment]
Isso, agora pra gente saber o que é framework oque é linguaguem e oque é outros, acho que vale a pena uns prefixos, 

> Mas ele teria de botar o nome do proj em algum canto né? não seria melhor colocar logo tudo lá?
 
Ele só precisa colocar o nome com o hiperlink, e a descrição pode ficar do jeito que tá. Ai no site a gente pode limitar o tamanho da descrição também.

**Comment by thayannevls** [comment]
Galera, acho que a gente poderia primeiro tentar iniciar com o que se tem. A github api já tem os dados que podemos usar pra fazer o esqueleto da coisa, que é mostrar esses repositórios, separar por linguagem e tags(As tags que o github permite você colocar). A api é simples e só seria usada no front. E daí tentar mostrar informações como Stars, Forks, Issues etc.

Entendi a parte da necessidade de separação por filtros que não existem no github, seriam por exemplo a separação de níveis de dificuldade certo? Acho que isso ficaria muito simples quando tivemos um cadastro no site, onde o dono do repositório pode nos oferecer essas informações num formulário e conseguiríamos fazer de maneira muito mais simples.

**Comment by thayannevls** [comment]
No caso eu priorizaria por agora conseguir mostrar esses repositórios com as informações que podemos extrair a vontade da githubApi. Única coisa que precisamos é o nome do repositório salvo em algum canto do código.

Depois disso podemos evoluir para mais filtros. Uma funcionalidade por vez

**Comment by thayannevls** [comment]
No caso poderia montar o json contendo o campo de que a gente conseguia mapear o repo pra github api e esse campo de dificuldade definido por nós

**Comment by joseims** [comment]
Se for so a dificuldade da pra colocar no layout

**Comment by joseims** [comment]
Sim, e com as opções de filtro por linguagem e frameworks (se a gente usar a ideia do prefixo que eu dei :v )

**Comment by JRobsonJr** [comment]
Oi, gente! Cheguei agora. Não sei se gosto muito da ideia de padronizar os READMEs, pensando especificamente nos projetos dos quais participo. Concordo com @JoseRenan que isso seria uma poluição do arquivo. Como @thayannevls comentou, dá pra usar a própria API do GitHub, basta encorajar o pessoal a usar as tags. 

Acho que algumas coisas já podem ter sido definidas nesse meio tempo, mas estou respondendo uma discussão por vez. Perdoem se algo que eu falei já está desatualizado. ;)

**Comment by thayannevls** [comment]
nada @JRobsonJr , a gente tá decidindo ainda haha.

Bem, a gente tem essa opção das tags mesmo, mas conversando com @JoseRenan a gente meio que quer aumentar o número de Forks rs... Então estávamos pensando em criar um *Json* que conteria alguma identificação do repositório(nome como exemplo), que ao incluir seu repositório lá, nós conseguiríamos fazer uma query na API do Github pra pegar as infos dele.

Só falta definir como seria a Json, e também implementar isso kkkkk, tá com previsão de isso ser adiciona na primeira versão e por enquanto tá sendo discutido aqui #21
