### ISSUE TITLE
Primeira versão, como fazer

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#14]
Nossos objetivos:

- Listar os repositórios da organização e os que apoiamos
- Adicionar separação dificuldades de codificação para cada projeto
- Fazer um deploy simples em algum canto

Discussão: Com o que e como será feito.

Sugestão: React e Github Api. React porque apesar de simples as tasks atuais, possibilita o crescimento e flexibilidade da aplicação no futuro.

Se entramos em acordo, começamos a separação de issues daqui.

**Comment by thayannevls** [comment]
Link inspiração: https://github.com/globocom/opensource

**Comment by JoseRenan** [comment]
Apoio o React, pq vai ter mais gente apta a contribuir (pelo menos que eu conheça kkkk), e é uma tecnologia rising na UFCG! Github API nn tem nem o que discutir, sobre os objetivos, pra versão 1.0 tá perfeito, vale adicionar que seria sem filtragem por enquanto, correto? só exibição

**Comment by thayannevls** [comment]
Sim, sim! Acho que já podemos criar umas tasks

**Comment by FannyVieira** [comment]
No caso @thayannevls a gente vai usar graphql pra api, certo?

**Comment by thayannevls** [comment]
Isso @FannyVieira , se tu puder ajudar a montar as queries depois

**Comment by JoseRenan** [comment]
Eu gostaria de solicitar a opinião de @Jrobsonjr sobre o que faremos nessa primeira versão, se ele concorda e se ele tem mais alguma sugestão :heart:

**Comment by FannyVieira** [comment]
@thayannevls seria bom ter uma pagina com os colaboradores(aka quem somos), e outra de como cadastrar o seu projeto aqui

**Comment by JRobsonJr** [comment]
Eu gosto da ideia de usar React e a API do GitHub. Acho que a gente consegue dar um gás pra fazer isso acontecer :) Bem, tem a questão de que as tags também poderiam ser submetidas pelos próprios desenvolvedores na hora de submeter um projeto, o que eu acho que não daria tanto trabalho de implementar e daria a possibilidade de botar umas tags bem específicas e que não fariam tanto sentido no GitHub (a questão da dificuldade, e até botar se algum projeto foi iniciado em alguma disciplina...)

**Comment by JRobsonJr** [comment]
Claro, isso que eu disse é a longo prazo mesmo.
