### ISSUE TITLE
Conceito de times

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#15]
> Pensei em levar o conceito de times para ter um melhor aproveitamento da comunidade. Tipo assim: Tenho um problema com vue e não sei como resolver ele. Independente de meu time ser formado em vue ou não, certamente terá pessoas que programem outros projetos em vue e talvez possa responder a minha questão mais de perto. Aí que entrariam os times. Os usuários poderiam ir se inscrevendo em times que pudessem ajudar e isso facilitaria na hora de tirar dúvidas que não é possível simplesmente procurando em um stackoverflow da vida.

Dito por @JuanBarros2 na #13

**Comment by JoseRenan** [comment]
No caso o IssueAi mostraria os projetos e tbm mostraria grupos de pessoas pra cada tipo de expertise?

**Comment by FannyVieira** [comment]
Acho que isso se encaixa bem no que a gente tinha comentado sobre ter pessoas responsavéis por mentoria

**Comment by thayannevls** [comment]
Verdade @FannyVieira, então encontramos uma solução para isso de mentoria. 

@JoseRenan acho que seria legal :rabbit:, mas será uma pra-ja-issue-ai ou pra-jaja-issue-ai?

**Comment by joseims** [comment]
Acho top

**Comment by JoseRenan** [comment]
~Oi, @thayannevls KKKKKK~  eu ainda não entendi bem, acho que a gente devia colocar como pra-dps-issue-ai, porque não tá claro eu acho, e tá um pouco distante do escopo da primeira versão.. mas poderia ser um pra-jaja-issue-ai se a gente resumir esses teams em: mostrar as pessoas que tem projetos em determinadas áreas... pra quem a pessoa poderia pedir ajuda, mas ainda não estaria nessa versão, pq eu acho que deveria ter algum tipo de permissão do usuário pra ter seu nome lá sahuas vai que tem gente que não gosta de ser aperreado....

**Comment by JoseRenan** [comment]
> mostrar as pessoas que tem projetos em determinadas áreas...

Por exemplo: eu tenho um projeto em react, @jrobsonjr tb e @paulojbleitao tb, daí o showcase mostraria nossos nomes e o email pra contato associado ao github da gente dizendo que pode entrar em contato com a gente que a gente pode ajudar em react

**Comment by JuanBarros2** [comment]
Eu não pensei em uma aplicação pra isso galera. Pensei em utilizar a ferramenta que o github dá para fazer isso. Quem tivesse interesse em chamar o time do OpenDev poderia fazer de forma simples...

**Comment by JuanBarros2** [comment]
O problema maior é que essa feature só funciona dentro da organização, projetos que não tivessem linkado com a org não é possível referenciar o time...

**Comment by thayannevls** [comment]
Acho que por enquanto a gente poderia começar só com os times do github, ai quando tivemos a plataforma podemos adicionar esse feature
