### ISSUE TITLE
Animação de carregamento

### ISSUE THREAD

**Issue by danielmitre** [OpenDevUFCG/IssueAi#188]
**Descreva o bug**
A animação no botão de carregar mais issues não é exibida corretamente.

**Reprodução do bug**
1. Acesse https://issueai.opendevufcg.org/
2. Clique em "Ver Mais" e observe o botão tentar exibir a animação. (Pausar o javascript na aba debugger pode ajudar, se isso acontecer muito rápido)
3. Em vez da animação, é exibido apenas o alt "loader"

**Comportamento desejado**
Era esperado que aparecesse a animação dentro do botão de carregamento.

**Capturas de tela**
![image](https://user-images.githubusercontent.com/25506375/67626660-d9e9cc80-f824-11e9-8a05-003ec3a7a052.png)

**Desktop:**

-   SO: Linux-mint
-   Navegador: Firefox Quantum 69.0 (64-bit)

**Contexto adicional**
Debugando um pouco pelo navegador, encontrei um contexto similar [aqui](https://stackoverflow.com/q/18032220), onde diz que o webkit (opera, chrome, etc.) aceita o content na tag img.

**Comment by danielmitre** [comment]
Acredito que substituir a tag <img> por uma <div> é o modo que não afetaria nada mais do sistema. Alterando pelo navegador só pra confirmar que funciona:

![image](https://user-images.githubusercontent.com/25506375/67626777-d0616400-f826-11e9-8497-6f6ae5feff58.png)

Gostaria de ficar responsável por corrigir esse bug, se for confirmado.

**Comment by thayannevls** [comment]
Obrigada por reportar @danielmitre ! Ele realmente está acontecendo e foi reportado por usuários, seria ótimo se você pudesse ajudar a gente com isso! Vou te dar assign, quaisquer dúvidas ou sugestões pode falar por aqui.
