### ISSUE TITLE
Obter dados dos repositórios e mostrar

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#21]
- [x] Criar Repository componente
- [x] Fazer query que a partir do nosso, recupera os repositórios e seus dados da githubAPI
- [x] Criar modelo do Json de repositórios
- [x] Consumir do Json para fazer a pesquisa de repositórios na github API
- [x] Mostrar repositórios com informações na tela:
   - [x] Nome do repositório
   - [x] Número de stars, forks, issues e PRs
   - [ ] Dificuldade(Definida por nós no Json)
   - [x] Descrição

**Comment by FannyVieira** [comment]
Posso ajudar com a parte da query.

**Comment by thayannevls** [comment]
Também falta fazer a query pros projetos que são fora da organização, pra isso a gente precisaria criar aquele Json dos repositórios. Queria saber se tem um jeito de fazer uma query só pra pegar isso tudo, ou se teria que fazer separado.

**Comment by FannyVieira** [comment]
> Montei a estrutura inicial do componente e um rascunho do que seria a query, to precisando de ajuda pra fazer essa query sem colocar **first: 30**

Acho que da pra usar paginação, pra não precisar do **first: 30**

**Comment by FannyVieira** [comment]
> Também falta fazer a query pros projetos que são fora da organização, pra isso a gente precisaria criar aquele Json dos repositórios. Queria saber se tem um jeito de fazer uma query só pra pegar isso tudo, ou se teria que fazer separado.

Blz, vou tentar fazer agora de manhã.

**Comment by FannyVieira** [comment]
> Também falta fazer a query pros projetos que são fora da organização, pra isso a gente precisaria criar aquele Json dos repositórios. Queria saber se tem um jeito de fazer uma query só pra pegar isso tudo, ou se teria que fazer separado.

Acho que tem como fazer pra pegar tudo, mas a gente teria que ter um indicador pra saber que é do ISSUE-AI, no da globo eles conseguem pegar todos os repos como facilidade, porque todos eles pertencem a organização deles.

**Comment by thayannevls** [comment]
Por isso o json fanny, só tem que saber que campo seria legal
