### ISSUE TITLE
Código em português ou em inglês?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#23]

**Comment by JRobsonJr** [comment]
Boa pergunta! Como nós estamos querendo tratar de open source e introduzir isso a outros alunos do curso, eu acredito que o código e as contribuições em geral (mensagens de commit, por exemplo) deveriam ser escritos em inglês. Eu acredito que vivenciar esse ambiente em inglês vai contribuir de várias formas, especialmente no que se refere a criar um costume com o vocabulário da área e também facilitar a comunicação com outros em inglês. Entretanto, isso também pode ser a critério dos desenvolvedores de um projeto específico e do escopo do projeto. Por exemplo, nos projetos do calluswhatyouwant, meu desejo é manter tudo em inglês para não limitar os contribuidores a falantes de português.

**Comment by FannyVieira** [comment]
Concordo @JRobsonJr, acho que como o foco da gente também são os novatos, poderiamos    desenvolver os apps em inglês, ja que eles requerem uma experiencia maior, e deixa a documentação e o tamburetei com as duas opcões (portugues e inglês) já que eles são mais amigaveis no sentido de fazer as primeiras contribuições e não perdemos a questão do público.

**Comment by thayannevls** [comment]
Vai ser assim então pessoal :)

**Comment by JoseRenan** [comment]
Decidido então.... fechando :heart:
