### ISSUE TITLE
Criar um CONTRIBUTING.md

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#26]
Necessário a criação de um **CONTRIBUTING.md** contendo guias de como rodar o projeto, e regras para abrir issues e pull requests, especificando a necessidade do código e commits serem em inglês.

**Comment by thayannevls** [comment]
@JoseRenan Preciso de ajuda pra dar informações sobre o Flow e o estilo de código, assim como ajudar o contribuinte a configurar essas coisas

**Comment by JoseRenan** [comment]
Acho que essas coisas podem ser explicadas na revisão, caso o contribuidor não consiga encontrar padrão nos outros arquivos. As configurações a gente pode sugerir (tipo extensão no VSCode), mas não é obrigatório também, o lint vai rodar no CI e o flow tbm, o estilo o prettier roda no pre-commit, então não precisa detalhar mto isso, a gente precisa explicar onde encontrar issues, explicar as labels, explicar como adicionar seu projeto, explicar como contribuir pra algum PR em andamento, como sinalizar que tá fazendo algo, etc

**Comment by JoseRenan** [comment]
Sobre sinalizar que está fazendo algo, eu recomendo que a gente peça que ele crie um PR com [WIP] começo do título e referencie a issue que ele quer pegar, mesmo que o PR nn tenha alterações, só pra gente acompanhar o progresso

**Comment by thayannevls** [comment]
Não precisa de muitos detalhes mesmo não, mas é bom explicitar que estilo de código se usa

**Comment by thayannevls** [comment]
@JoseRenan conhece algum exemplo bom?

**Comment by fanny** [comment]
Eu conheço [esse](https://github.com/elsewhencode/project-guidelines)
