### ISSUE TITLE
Tamburetei

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#3]
Tamburetei é um repositório que vai te ajudar a fazer de tamburete aquela cadeira de CC. A ideia é que pessoas que já pagaram as cadeiras ajudem que está pagando.

Agora vem o *Como?* da questão. 

Ideias que pensei:

- MDs contendo Tips e Hacks, que no caso seriam links muito úteis, ou coisas como os scripts que usam em LEDA
- Seria arriscado colocar leites? @FannyVieira e @JuanBarros2 viram a necessidade de um repositório colaborativo para leites, esse poderia fazer parte
- Talvez padronizar os textos que cada disciplina tem que ter, imagino de cara os "Hacks e Tips", tbm algum como "Dificuldades e como superei", talvez um "Como estudar" para aquela cadeira em especifico
- Muito importante ter um código de conduta e um manual bem definido de como pode se colaborar, só não sei cm ainda
- De alguma forma incentivar a conversa por issues nesse repositório, para que as pessoas consigam discutir o que mais ajudou naquela cadeira

**Comment by FannyVieira** [comment]
A ideia dos leites, é see algo parecido com o passei direto e como o famoso dropbox "Galhera CC", só que o ruim do passei direto é que não é algo direcionado pra UFCG, por vezes é ruim encontrar algum material de certas discuplinas, principalmente especificas, o ruim do galhera é que está desatualizado, nossa ideia é conseguir solucionar esses problemas.

**Comment by FannyVieira** [comment]
Penso também se seria legal, ou como a gente incluiria resumos, tem muitas cadeiras teóricas, que geralmente os professores passam muitos slides(ex: bd, redes..), que é legal você ter um resumo ou um mapa mental

**Comment by joseims** [comment]
Seria tipo um Medium só de resumos e ettc?

**Comment by thayannevls** [comment]
Oi @joseims , acho que também. Queria também compartilhar alguns links ou materiais úteis que geralmente a gente sai compartilhando no curso, quem sabe algumas implementações. O difícil é saber como padronizar isso no repositório

**Comment by JoseRenan** [comment]
Pelo que entendi conversando com @JuanBarros2 seria tipo tips de várias cadeiras, pra pessoa saber o que esperar e ter sempre coisas atualizadas da cadeira, de gente que pagou, tipo, no período anterior

**Comment by thayannevls** [comment]
Só to na dúvida se vale a pena botar uns leites e deixar a galera upar, acho que vou criar e formando uma discussão lá

**Comment by joseims** [comment]
A gente poderia até falar com uns profs pra eles botarem os monitores pra fazer/atualizar conteudo e exercicios. Acho que alguns topariam. 
Acho que se a gente for fazer tipo um medium, a gente não precisa se preocupar muito, se alguem quiser upar um leite dentro de um documento é ok.

**Comment by thayannevls** [comment]
@joseims @FannyVieira criei o repositório e tentei definir os padrões, se quiserem dar uma discutida lá 😄
