### ISSUE TITLE
Fazer página 'Quem somos?'

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#34]
em `quem-somos/` tem que se ter uma descrição básica e também uma listagem de todos os membros da organização.

- [ ] Fazer query para obter membros da organização

- [ ] Mostrar os membros

- [ ] Contagem de membros

**Comment by fanny** [comment]
@ArthurFerrao Essa é a secao dos times, comenta aqui

**Comment by ArthurFerrao** [comment]
@fanny opa, só vi agora isso aqui
