### ISSUE TITLE
Configurar para fazer deploy ao commitar no master

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#37]
Ao commitar no master, já deve subir uma versão para deploy em https://issue-ai.appspot.com/

**Comment by JoseRenan** [comment]
Corrigido no merge #41

**Comment by JoseRenan** [comment]
Na verdade não corrigiu não KKKKKKKKK fez deploy mas fez errado

**Comment by thayannevls** [comment]
KKKKKKKKKKKK bem, pelo menos reverteu. A gnt vê dps como ajeitar isso

**Comment by JoseRenan** [comment]
@thayannevls isso já tá sendo feito pro gh-pages né?

**Comment by thayannevls** [comment]
Sim :)

**Comment by JoseRenan** [comment]
Resolvido no #56
