### ISSUE TITLE
Erro no console

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/IssueAi#45]
Ao entrar no [site appspot](https://issue-ai.appspot.com) ou localmente, aparece o seguinte erro no console:

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of 'RepositoryGrid'.`

**Comment by juliobguedes** [comment]
Já implementei a correção disso, mas não consigo criar novas branches aqui pra fazer o MR...

**Comment by thayannevls** [comment]
Tinha esquecido de erro, boa!

Se tu quiser virar um contribuidor frequente do IssueAi posso te adicionar o time pra tu fazer uma branch por aqui e ai tu contribui. Se não tu pode submeter com Fork

**Comment by juliobguedes** [comment]
Me adiciona, achei no time do react eu teria essa permissão por default, já vou ficar ajudando sempre que possível

**Comment by thayannevls** [comment]
Adicionado :D
