### ISSUE TITLE
O que mostrar na palestra da Semana do fera

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#50]
Iremos ter uma palestra de provavelmente 50min~60min na semana do fera, com o intuito de mostrar o OpenDevUFCG como uma iniciativa estudantil. Essa issue será feita de discussão pra isso.

O que mostrar? Como mostrar? Como organizar? Quais ideias vocês tem?

**Comment by thayannevls** [comment]
Precisamos elaborar uma forma de mostrar o que é Open Source e o contexto do OpenDev para pessoas que nunca programaram na vida, esse vai ser o nosso maior desafio.

Pensei em começar mostrando esse [vídeo](https://youtu.be/HzZxcfVn_08) que foi na verdade o que deu o início ao brainstorming de eu e Renan sobre o IssueAi e o que poderia ser alçando na ufcg. O que acham?

**Comment by JuanBarros2** [comment]
Primeiro ponto que acho importante é como iremos introduzir os feras no que é o open source. Acho que é bom introduzir bem o que isso significa porque várias pessoas entram 100 % leigas em o que é computação e não sabem nem o que o github representa.

**Comment by FannyVieira** [comment]
> Primeiro ponto que acho importante é como iremos introduzir os feras no que é o open source. Acho que é bom introduzir bem o que isso significa porque várias pessoas entram 100 % leigas em o que é computação e não sabem nem o que o github representa.
Sim, concordo. Acho que é bom interagir também mostrando o que eles são capazes de fazer com o open source, tipo, ajudar a melhorar uma ferramenta que eles gostam, casos proximos da gente que fizeram isso, pra eles entenderem que isso é possivel pra qualquer pessoa, e as oportunidades que podem surgir cm isso tb

**Comment by JuanBarros2** [comment]
> Precisamos elaborar uma forma de mostrar o que é Open Source e o contexto do OpenDev para pessoas que nunca programaram na vida, esse vai ser o nosso maior desafio.
> 
> Pensei em começar mostrando esse [vídeo](https://youtu.be/HzZxcfVn_08) que foi na verdade o que deu o início ao brainstorming de eu e Renan sobre o IssueAi e o que poderia ser alçando na ufcg. O que acham?

Interessante o vídeo, mas acho que é pouco tempo de apresentação e, mesmo sendo curto, acho que o seria melhor se a gente mesmo passasse a mensagem dele.

**Comment by thayannevls** [comment]
Como passar essa mensagem então?

**Comment by JoseRenan** [comment]
> Sim, concordo. Acho que é bom interagir também mostrando o que eles são capazes de fazer com o open source, tipo, ajudar a melhorar uma ferramenta que eles gostam, casos proximos da gente que fizeram isso, pra eles entenderem que isso é possivel pra qualquer pessoa, e as oportunidades que podem surgir cm isso tb

Eu acho uma boa desmistificar algumas coisas de open source, tipo, quando eu pensava em open source, eu pensava em ficar fuçando na internet por zips com o código e tal e dificil comunicação etc

**Comment by JuanBarros2** [comment]
> > Sim, concordo. Acho que é bom interagir também mostrando o que eles são capazes de fazer com o open source, tipo, ajudar a melhorar uma ferramenta que eles gostam, casos proximos da gente que fizeram isso, pra eles entenderem que isso é possivel pra qualquer pessoa, e as oportunidades que podem surgir cm isso tb
> 
> Eu acho uma boa desmistificar algumas coisas de open source, tipo, quando eu pensava em open source, eu pensava em ficar fuçando na internet por zips com o código e tal e dificil comunicação etc

Mas acho que boa parte não sabe nem o que é git

**Comment by JoseRenan** [comment]
> Mas acho que boa parte não sabe nem o que é git

Mas dá pra mostrar que com uma busca no google vc acha o código, que é de fácil acesso e tal
![image](https://user-images.githubusercontent.com/11728746/52310840-8e844b00-2983-11e9-9c9d-443aa4592667.png)
