### ISSUE TITLE
Token de acesso a API do github não usado corretamente

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#51]
Atualmente estou configurando o [IssueAi para o github pages](#49 ), porém o GitHub parece estar apagando o token que usamos para acessar dados da API toda vez que o deploy é concluído. Talvez estejamos violando o uso do Token e precisa ser feito de outra forma.

#49

**Comment by thayannevls** [comment]
Bem pelo que estou lendo, não é pra usar o Personal Access Token como estamos fazendo, mas sim configurar o IssueAi no Github Apps ou OAuth Apps

**Comment by thayannevls** [comment]
Não vi uma explicação para o github estar removendo o token sem avisar

**Comment by thayannevls** [comment]
O GitHub está detectando o token no [commit feito no bundle]( https://github.com/OpenDevUFCG/IssueAi/blob/18628ae86e7feaa552f3075765b0f46a4e9efdc8/bundle.0d88848d8541dbe31a08.js) e detectando como atividade maliciosa e apaga o Token pra proteger minha conta.

**Comment by thayannevls** [comment]
Solução que vi foi criptografar a variável contendo o token usando o travis, vamos ver se funciona

**Comment by JoseRenan** [comment]
Com a issue #53 esse problema será resulvido
