### ISSUE TITLE
Fazer o IssueAi usar a laguinho-api para os dados

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#53]
Os dados dos nossos repositórios foram transferidos para a [OpenDevUFCG/laguinho-api](https://github.com/OpenDevUFCG/laguinho-api).

O ideial é que agora o IssueAi consuma os dados de lá, e que já comece a fazer o deploy no gh-pages já configurado aqui #49

**Comment by JoseRenan** [comment]
Vale lembrar que o laguinho tá hospedado em laguinho.opendevufcg.org
