### ISSUE TITLE
Adicionar documentação sobre a nova forma de obter dados

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#54]
Para um repositório aparecer no IssueAi, ele deve ser adicionado na [Laguinho API](https://github.com/OpenDevUFCG/laguinho-api), neste [arquivo](https://github.com/OpenDevUFCG/laguinho-api/blob/master/src/v1/repositories/repo-data.js).

É preciso modificar no README e no CONTRIBUTING sobe como adicionar seu projeto a nossa lista de apoiados, e direcionar o nosso usuário para lá caso ele queira mexer nos dados.

**Comment by JoseRenan** [comment]
Resolvido no #56
