### ISSUE TITLE
Adicionar Hint no site

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/IssueAi#57]
Ao colocar o mouse sobre os ícones (as estrelas, o talher, etc), deveria aparecer algo que informe ao usuário o que aquele contador significa, uma espécie de hint ou tooltip

**Comment by wandersonpsantos** [comment]
Posso ajudar com esse.

**Comment by thayannevls** [comment]
Opa @wandersonpsantos, muito obrigada! Sinta-se livre pra pedir ajuda ou tirar dúvidas

Estamos no [discord](https://discordapp.com/invite/vFFGGEE) também.
