### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#6]
Costumo escolher licenças de maneira descontraída, mas acho que talvez valha a pena uma pequena discussão. A licença que usamos aqui, pode servir de default para projetos futuros

Talvez a [GPL v3.0](https://choosealicense.com/licenses/gpl-3.0/) seja a mais indicada, acho que o que eu teria a reclamar é que obriga aos que usarem nosso projeto a usarem a mesma licença
 
#1

**Comment by thayannevls** [comment]
Acabei mudando de ideia e preferindo a [MIT](https://choosealicense.com/licenses/mit/)

**Comment by thayannevls** [comment]
Na verdade a [MIT](https://choosealicense.com/licenses/mit/) é mais vantajosa pro nosso contexto

**Comment by JoseRenan** [comment]
Acredito que MIT sai melhor, pq ela é bem permissiva, a única restrição é creditar o projeto original, por mim acho que tá perfeito assim, fica aberto pra usar como quiser e modificar como quiser
