### ISSUE TITLE
Plataforma para solucionário da Poscomp

### ISSUE THREAD

**Issue by ivynasantino** [OpenDevUFCG/IssueAi#67]
Pensando na facilidade de reunir provas+soluções da poscomp e aliado com a proporção de pessoas que a opendev está atingindo, acho interessante o desenvolvimento de um site para reunir solucionários. Inicialmente, pensei na poscomp por ter escala nacional e é o exame realizado para entrada de alunos no mestrado da UFCG, mas para próximos passos, poderia daptar também para o Enade, como exemplo. O que vocês acham?

**Comment by thayannevls** [comment]
ping @JuanBarros2 @lucasmedeiros @JoseRenan @juliobguedes @SpinnelSun @JRobsonJr

**Comment by SpinnelSun** [comment]
Eu acho a ideia ótima, não só porque é uma ferramenta muito útil a nível nacional (já que os materiais de estudo pra POSCOMP ficam bem difusos por aí), mas também pelos benefícios que viriam pra organização. Seria uma forma muito interessante de engajar o pessoal dos últimos períodos do curso, um público que a gente ainda tem certa dificuldade de alcançar.

Por mim, já tá eleito como um novo projeto da OpenDevUFCG.

**Comment by juliobguedes** [comment]
Assim como comentei informalmente com os meninos, existe o [Poscomp Coach](https://poscompcoach.com/landing/) que funciona como uma forma de simulados para o poscomp, mas não tá opensource (o link pro source code não permite acesso pra mim, pelo menos). Acho a ideia excelente e um ótimo projeto pra desenvolver no OpenDev, principalmente com o PosComp desse ano chegando :)

Se o PET puder contribuir e fornecer os solucionários dos anos anteriores, a gente podia fazer uma plataforma parecida com o PosComp coach e ainda incluir as soluções pras questões... Depois, ainda dá margem pra fazer sistema de recomendações e esse tipo de coisa, pra medir qual a área de CC que o usuário tá mais forte/mais fraco, recomendar questões disso, etc

**Comment by ivynasantino** [comment]
Falei com alguns petianos sobre essa ideia e eles se disponibilizavam a ajudar com os solucionários. Gostei da ideia de recomendação, acredito que isso seria um diferencial na ferramenta.

**Comment by SpinnelSun** [comment]
Então... Todo mundo de acordo que esse é o novo projeto do @OpenDevUFCG?

**Comment by fanny** [comment]
simm!

**Comment by alvesmatheus** [comment]
O projeto foi criado, discussões futuras devem ser realizadas [aqui](https://github.com/OpenDevUFCG/poscomp).
