### ISSUE TITLE
Adicionar loading quando está carregando os projetos

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#71]
Seria bom quando estamos fazendo requisição para pegar a lista de projetos, e está resolvendo a promise, apareça uma animação informando que está carregando para página não ficar vazia.

Extra: O botão "Ver mais" poderia ter uma animação de carregando quando clicasse nele

**Comment by ArthurFerrao** [comment]
Quero fazer essa, posso pegar?

**Comment by thayannevls** [comment]
Claro! @ArthurFerrao
