### ISSUE TITLE
Número de cards de projeto não preenchem a tela

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#72]
**Descreva o bug**
 O IssueAi faz a requisição de 10 repositórios inicialmente, e essa quantidade nem sempre preenche a tela, dando uma sensação de quebra.

**Comportamento desejado**
Que o número cards por coluna fossem iguais sempre que possível.

**Capturas de tela**
<img width="1680" alt="Screen Shot 2019-10-02 at 21 40 48" src="https://user-images.githubusercontent.com/6867958/66091252-67573b00-e55d-11e9-8780-6bbb23c70e5b.png">

**Comment by wdtamagi** [comment]
Posso ajudar com issso.

**Comment by thayannevls** [comment]
Muito obrigada @wdtamagi , sinta-se livre para tirar dúvidas! Estamos no [discord](https://discordapp.com/invite/vFFGGEE) também.

Informação que pode ajudar: Esses dados de repositórios são consumidos dessa [API](https://github.com/OpenDevUFCG/laguinho-api)

**Comment by wdtamagi** [comment]
Show @thayannevls !
Obrigado.
