### ISSUE TITLE
Mudar direção de opções do menu em telas menores

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/IssueAi#73]
Atualmente em telas menores o "Quem somos?" e "Contribuir" ficam na vertical
<img width="274" alt="Screen Shot 2019-10-02 at 22 18 27" src="https://user-images.githubusercontent.com/6867958/66092544-bb185300-e562-11e9-8f2c-cc8eba991b5b.png">

Há espaço para eles ficarem lado a lado em algumas telas pequenas, e é mais agradável visualmente.

O que pode ser feito: Quando pode, os items do menu ficam na mesma linha, quando não cabe na tela, se quebra para ficar um abaixo do outro. Isso pode ser feito usando [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by evelew** [comment]
Eu posso corrigir isso :)

**Comment by thayannevls** [comment]
Muito obrigada @evelew , se precisar de qualquer ajuda pode falar por aqui! Também temos um channel no [discord](https://discordapp.com/invite/vFFGGEE)
