### ISSUE TITLE
Criar nova seçao para exibiçao dos mentores dos projetos

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/IssueAi#76]
**Descrição da melhoria:**
Seria legal conseguir identificar quais sao os mentores de cada projeto que o Issueai apoia, para ajudar os contribuidores saberem a quem recorrer.

**Como ela pode ser implementada:**
Uma nova pagina `/mentores` seria desenvolvida, onde seriam listados os mentores dos projetos que apoiamos, essa pagina seria referenciada no menu do nosso projeto.

**Comment by ArthurFerrao** [comment]
Quero tentar

**Comment by fanny** [comment]
Claro, faremos juntos!
