### ISSUE TITLE
Aproveitar o espacamento do header em telas pequenas

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/IssueAi#79]
**Descrição da melhoria:**
Em algumas telas, os componentes do header podiam ser exibidos na mesma linha, mas sao truncados.

**Como ela pode ser implementada:**
alteracao de algumas propriedades do css do `Header`, como `flex-wrap` e `margin`s.

**Imagens:**

![image](https://user-images.githubusercontent.com/14113480/66097199-7ba23480-e56b-11e9-91f1-0ae4d89df363.png)

**Comment by GuiMouraIgnacio** [comment]
Posso tentar corrigir isso? 😄

**Comment by fanny** [comment]
Corrigido na pr #77
