### ISSUE TITLE
Fazer página para 'Junte-se a nós'

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/IssueAi#80]
**Descrição da melhoria:**
Criar uma pagina`/junte-se` com informacoes detalhadas sobre como ter o seu repositório apoiado por nós, e sendo assim exibido na nossa lista.

**Comment by fanny** [comment]
cc @arthurferrao

**Comment by lucasmedeiros** [comment]
Posso fazer? :p

**Comment by fanny** [comment]
Claro @lucasmedeiros, pra fzr ela tu vai precisar planejar só o textinho de como o pessoal deve colocar o projeto aqui e validar umas coisas de desogn comigo e @arthurferrao

**Comment by thayannevls** [comment]
Essa página poderia ser markdown, ver como renderizar ela se for

Acho mais fácil e prático, já que vai ser uma explicação textual

**Comment by lucasmedeiros** [comment]
@thayannevls Okay, vou fazer isso

**Comment by lucasmedeiros** [comment]
@thayannevls Onde esse arquivo `.md` ficaria? Teria uma pasta específica com outros? Porque se fosse só nesse que fosse usado MarkDown, acho que seria bem estranho...
