### ISSUE TITLE
Abrir uma nova guia ao clicar em um projeto

### ISSUE THREAD

**Issue by Rickecr** [OpenDevUFCG/IssueAi#88]
**Descrição da melhoria:**
Fazer com que ao usuário clicar em um projeto, este projeto seja aberto em uma nova guia. 

**Necessidade da melhoria:**
As vezes o usuário quer abrir mais de um repositório, e assim ele teria que clicar com botão direito e `Abrir link em nova guia`. Colocando para os projetos serem abertos em uma nova guia, automaticamente, facilitaria na navegação do usuário. 

**Como ela pode ser implementada:**
Colocando a propriedade target do CSS nessa [linha](https://github.com/OpenDevUFCG/IssueAi/blob/826f8acbdf668de12e5ff00a0120596a1cfb6414/src/components/commons/repository/RepositoryCard.js#L52).

**Comment by thayannevls** [comment]
Acho muito válido @Rickecr !

Tu tem interesse em fzr essa task?

**Comment by Rickecr** [comment]
Posso fazer sim.
