### ISSUE TITLE
Configurar bot para gerenciar o controle de issues

### ISSUE THREAD

**Issue by FannyVieira** [OpenDevUFCG/IssueAi#9]
Lendo o readme, eu vi o problema de você ter que ficar checando se a issue já existe, mas existem algumas ferramentas pra fazer esse controle, seria bom darmos uma pesquisada e se for o caso configurá-la aqui.

**Comment by thayannevls** [comment]
Oi @FannyVieira , parece que o github implementou essa funcionalidade essa semana, só não testei ainda.

**Comment by FannyVieira** [comment]
Eu já tinha visto alguns, mas não são oficiais, são desenvolvidos por terceiros, alguns exemplos: [probot](https://github.com/probot/stale), [babel-bot](https://github.com/babel/babel-bot)

**Comment by thayannevls** [comment]
Acho que como agora é nativo do github, seja melhor deixar por enquanto sem pra testar

**Comment by JoseRenan** [comment]
O que é o controle de issues que tu fala? @FannyVieira

**Comment by FannyVieira** [comment]
Oi @JoseRenan, é mais pra verificar se uma issue já existe, tem uns bots que avaliam se o texto da issue que você está submetendo, é muito similar a algum existente, e automaticamente lhe manda o link e fecha a issue, remove issues que estão inativas por muito tempo, remove branchs que ja foram "merjadas", esse tipo de coisa.

**Comment by thayannevls** [comment]
Esse de remover issues automaticamente é mto bom, não sabia. Acho que a gente pode tentar ver se o nativo do github é o suficiente, se a gente começar a perder o controle, a gente adiciona esse bot.

O que acha?

**Comment by JoseRenan** [comment]
Se for ctz isso do bot "nativo", por mim taok assim
