### ISSUE TITLE
Adicionar ranking de contribuidores para o Hacktoberfest

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/IssueAi#93]
**Descrição da melhoria:**
Como o título diz.

**Necessidade da melhoria:**
Seria legal ter um ranking com o top 10 de contribuidores durante esse mês festivo do opensource.

**Inspiracoes**
https://github.com/shubhsherl/GSoC-Contribution-Leaderboard

**Comment by fanny** [comment]
cc @ArthurFerrao

**Comment by ArthurFerrao** [comment]
opa
