### ISSUE TITLE
A Logo não aparece

### ISSUE THREAD

**Issue by Rickecr** [OpenDevUFCG/IssueAi#96]
**Descreva o bug**
O que título descreve.

**Reprodução do bug**
Abrir a página inicial do site.

1. Vá para [IssueAi](https://issueai.opendevufcg.org/)

**Comportamento desejado**
A logo fosse mostrada.

**Capturas de tela**
![image](https://user-images.githubusercontent.com/25726888/66391002-4f8b1700-e9a2-11e9-9e3d-6d5906e25c70.png)

**Desktop:**

-   SO: Linux Mint
-   Navegador: chrome

**Comment by thayannevls** [comment]
Oi @Rickecr ,

Estranho porque testei aqui e aparece, tu poderia abrir teu console e chegar se aparece algum erro quando recarrega a página?

**Comment by Rickecr** [comment]
![image](https://user-images.githubusercontent.com/25726888/66416953-626b0f00-e9d5-11e9-94db-8ebd9cacd7ce.png)

**Comment by wdtamagi** [comment]
Aqui está ok, sera q nao é algum bloqueio da sua rede ao imgur?
De qualquer forma seria uma boa prática incluir a imagem da logo no projeto e nao utilizar uma fonte externa.

**Comment by Rickecr** [comment]
Realmente era meu computador.

![image](https://user-images.githubusercontent.com/25726888/66528626-02f52800-ead7-11e9-884d-eb648d8499ff.png)
